[package]
name = "c2a-dev-runtime"
description = "Common C2A runtime for development"
version.workspace = true
edition = "2021"

[lib]
test = false   # 呼んでいる C2A の関数をリンクできないので，unit test はしない（できない）
# TODO: 適切な c2a-core とマッチした example user をリンクしたテスト

[dependencies]
c2a-core = "4.3.0"
