[package]
name = "c2a-bind-utils"
description = "C2Aのモジュールをbindgenするときのユーティリティ"
repository.workspace = true
version.workspace = true
edition = "2021"

license = "MIT"

[dependencies]
bindgen = "0.72.0"
doxygen-rs = "0.4.2"

# force set version to *NOT* to update MSRV by PATCH VERSION to build with Rust 1.76
home = "=0.5.9"
