name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  mobc:
    name: mobc
    uses: arkedge/workflows-c2a/.github/workflows/build.yml@v4.5.3
    with:
      c2a_dir: examples/mobc
      c2a_custom_setup: |
        cd ../..
        pwd
        ls -l
        if [ $RUNNER_OS = 'Windows' ]; then
          cmd "/C setup.bat"
        else
          ./setup.sh
        fi

  subobc:
    name: subobc
    uses: arkedge/workflows-c2a/.github/workflows/build.yml@v4.5.3
    with:
      c2a_dir: examples/subobc
      c2a_custom_setup: |
        cd ../..
        pwd
        ls -l
        if [ $RUNNER_OS = 'Windows' ]; then
          cmd "/C setup.bat"
        else
          ./setup.sh
        fi
