name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        user:
          - mobc
          - subobc

    uses: arkedge/workflows-c2a/.github/workflows/build.yml@v5.4.0
    with:
      c2a_dir: examples/${{ matrix.user }}
      c2a_custom_setup: |
        cd ../..
        pwd
        ls -l
        if [ $RUNNER_OS = 'Windows' ]; then
          cmd "/C setup.bat"
        else
          ./setup.sh
        fi
      build_msvc: true
      build_as_cxx: true
