name: check_coding_rule

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  check_coding_rule_v4:
    strategy:
      fail-fast: false
      matrix:
        user:
          - mobc
          - subobc
    uses: arkedge/workflows-c2a/.github/workflows/check-coding-rule.yml@cb46d1d34f43244e40506eb551204ea55357d661 # v6.0.2
    with:
      c2a_dir: examples/${{ matrix.user }}
      c2a_custom_setup: |
        cd ../..
        pwd
        ./setup.sh
