name: check_encoding

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  check_encoding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version-file: .github/workflows/.python-version
          architecture: 'x64'
      - run: pip install chardet
      - name: check_encoding
        run: python ./check_encoding.py ./check_encoding.json
        working-directory: ./script/ci
