name: check_coding_rule

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  check_coding_rule_v4:
    strategy:
      fail-fast: false
      matrix:
        user:
          - mobc
          - subobc
    uses: arkedge/workflows-c2a/.github/workflows/check-coding-rule.yml@092c8dff10cf5eb6d3af4c3b47bc5b57fe07e633 # v5.4.0
    with:
      c2a_dir: examples/${{ matrix.user }}
      c2a_custom_setup: |
        cd ../..
        pwd
        ./setup.sh
