name: Deploy C2A Reference

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: "pages"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: install deps
        run: |
          sudo apt-get update -y
          sudo apt install -y doxygen graphviz

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: C2A setup
        run: ./setup.sh

      - name: Build Doxygen
        run: doxygen

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: docs/html

  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
