name: labeler

on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - .github/workflows/labeler.yml
      - .github/labels.yml

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: ${{ github.ref != 'refs/heads/develop' }}
