name: pytest

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        include:
          # mobc pytest matrix(splitted because super-slow)
          - c2a_user: mobc
            test_dir: src_core/applications
          - c2a_user: mobc
            test_dir: src_core/system/event_manager/test_event_handler.py
          - c2a_user: mobc
            test_dir: src_core/system/event_manager/test_event_logger.py
          - c2a_user: mobc
            test_dir: src_core/system/task_manager
          - c2a_user: mobc
            test_dir: src_core/system/watchdog_timer
          - c2a_user: mobc
            test_dir: src_core/system/mode_manager
          - c2a_user: mobc
            test_dir: src_core/system/time_manager
          - c2a_user: mobc
            test_dir: src_core/tlm_cmd
          # 2nd_obc_user
          - c2a_user: subobc
            test_dir: .

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        submodules: recursive

    - name: install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc-multilib g++-multilib

    - name: setup c2a-core
      run: ./setup.sh

    - uses: pnpm/action-setup@v4.0.0
      with:
        package_json_file: examples/${{ matrix.c2a_user }}/package.json

    - uses: actions/setup-node@v4.1.0
      with:
        cache: pnpm
        cache-dependency-path: examples/${{ matrix.c2a_user }}/pnpm-lock.yaml

    - name: Cache C2A devtools
      id: cache-c2a-devtools
      uses: actions/cache@v4.1.2
      with:
        path: |
          ./examples/mobc/tools/bin
          ./examples/mobc/tools/.crates.toml
          ./examples/mobc/tools/.crates2.json
        key: ${{ matrix.c2a_user }}-${{ runner.os }}-tools-${{ hashFiles('${{ matrix.c2a_user }}/tools/install.sh', '${{ matrix.c2a_user }}/tools/package.json') }}

    - name: Get Rust toolchain
      id: toolchain
      run: |
        awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain.toml >> "$GITHUB_OUTPUT"

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ steps.toolchain.outputs.toolchain }}
        targets: i686-unknown-linux-gnu
        components: clippy, rustfmt

    - name: cache Rust dependencies
      uses: Swatinem/rust-cache@v2.7.5

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: sksat/setup-rye@v0.31.0

    - name: install pytest deps
      working-directory: examples/${{ matrix.c2a_user }}/src/src_user/test
      run: |
        rye sync

    - name: the heaviest objects in universe
      working-directory: ./examples/mobc
      run: |
        pnpm install --frozen-lockfile

    - name: build mobc C2A
      if: matrix.c2a_user == 'subobc'
      working-directory: ./examples/mobc
      run: |
        cargo build --locked

    - name: build C2A
      working-directory: ./examples/${{ matrix.c2a_user }}
      run: |
        cargo build --locked

    - name: run mobc C2A
      if: matrix.c2a_user == 'mobc'
      working-directory: ./examples/mobc
      run: |
        pnpm run devtools:sils &
        sleep 3
    - name: run C2A (mobc & subobc)
      if: matrix.c2a_user == 'subobc'
      working-directory: ./examples/mobc
      run: |
        npm run devtools:sils-subobc &
        sleep 3

    - name: run pytest
      working-directory: ./examples/${{ matrix.c2a_user }}/src/src_user/test
      run: |
        rye run pytest -m sils -v ./${{ matrix.test_dir }}
