name: reviewdog / lint python

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flake8_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          level: warning
