name: Rust

on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:

env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain.toml >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          targets: i686-unknown-linux-gnu
          components: clippy, rustfmt

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.7.7

      - name: setup c2a-core
        run: ./setup.sh

      - name: reviewdog / clippy
        uses: sksat/action-clippy@v1.1.0
        with:
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          clippy_flags: --workspace --all-features --locked

      - name: format
        run: cargo fmt --all -- --check

      - name: unit test
        run: cargo test --workspace
