name: Rust

on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:

env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain.toml >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          targets: i686-unknown-linux-gnu
          components: clippy, rustfmt

      - name: cache dependencies
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

      - name: setup c2a-core
        run: ./setup.sh

      - name: reviewdog / clippy
        uses: sksat/action-clippy@87e08e0c289f2654fe702b0aaf88c2f1027a3e57 # v1.1.1
        with:
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          clippy_flags: --workspace --all-features --locked

      - name: format
        run: cargo fmt --all -- --check

      - name: unit test
        run: cargo test --workspace
